### ISSUE TITLE
DNSSEC DANE considerations

### ISSUE THREAD

**Issue by NiklausHofer** [E-404/Manifestos#3]
DNSSEC DANE entries allow verification of TLS certificates against a DNSSEC record instead of a public certificate authority. In theory, this allows a user to create a self-signed certificate or a certificate signed with their own CA which can be verified by anyone using DNSSEC.

This has been implemented for Prosody [0] but unfortunately I was unable to find an implementation for ejabberd.

You should consider allowing self signed certificates IF (and only if) they are secured by a proper DNSSEC entry.

[0] https://modules.prosody.im/mod_s2s_auth_dane.html

**Comment by E-404** [comment]
Developers ejabberd here https://github.com/processone/ejabberd
