### ISSUE TITLE
Fix the wording for 'self-signed' certificates

### ISSUE THREAD

**Issue by NiklausHofer** [E-404/Manifestos#4]
Your title states: 

> Servers in this list pledge not to accept connections with self-signed certificates.".

Technically this only covers actually self-signed certificates. That is to say x509 certificates that have been signed by the private key which's public key equivalent is included in the very certificate.

Presumably you also want to exclude certificates signed by CA's which are not widely recognized.

For example, I can create my own CA and use this CA to sign my certificate. This certificate is not technically self-signed, but it should still be mistrusted.

So the wording should be something like 

> Servers in this list pledge to only accept connections secured with certificates issued by widely recognized certificate authorities

**Comment by E-404** [comment]
ok. change to:
`Servers in this list pledge not to accept connections with untrusted certificates.`
